server:
  port: 9090
  jsp-servlet:
    init-parameters:
      development: true     #开发模式部署 即热部署 ，不需要重启服务器修改JSP
spring:
  mvc:
    view:
      prefix:
      suffix:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.ricrdowang.cn:3306/SillyOrdering?&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456789
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.bean,com.utils  #取别名
  configuration:
    map-underscore-to-camel-case: true #开启驼峰
logging:
  level:
    root: info      #指定根日志级别
    com.mapper: debug    #监听指定包中的日志，可以多个
